databases:
  - name: growthroom_db
    databaseName: growthroom_db
    user: growthroom_user
    plan: free

services:
  - type: web
    name: growthroom
    env: python
    buildCommand: rm -rf staticfiles && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && python manage.py createsuperuser && gunicorn growthroom.wsgi:application
    pythonVersion: '3.12'
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: growthroom_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: growthroom.onrender.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@growthroom.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin
#
Django superuser credentials for first-time setup:
Username: admin
Password: admin
Email: admin@example.com
