databases:
  - name: growthroom_db
    databaseName: growthroom_db
    user: growthroom_user
    plan: free

services:
  - type: web
    name: growthroom
    runtime: python
    pythonVersion: '3.12'
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: growthroom_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@growthroom.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin
