# Generated by Django 5.2.1 on 2025-06-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20250609_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='help_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='submission_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
