# Generated by Django 5.2.1 on 2025-06-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetask',
            name='employee',
        ),
        migrations.DeleteModel(
            name='EmployeeProject',
        ),
        migrations.DeleteModel(
            name='EmployeeTask',
        ),
    ]
