# Generated by Django 5.2.1 on 2025-06-22 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_training_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
